language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: M/G08oA42yYgwoUI9WP/hciyRUvKOR9Y/Xjn6/DplTjd5aEEDmmt/hEf254IRptrbiEhfNHVg99J1oYurNaWP8RtHf2GfqDMONzdR0lV4YzxOAS4gyxFUQrRadc6lq6DuptG6Zqq3znNReaCa1uGjyvQL2jiFmH9CPxjTjP+nzNUIpZyeE82yB3qkTyyABimUhSg8pYdWA0LqPd25+45n+gBmPZ4Dea2rnilPaOBLNnX3HWh2miaxQAFiRyIZ8LBP1CrF798eCOKryzIxIHbCudzuILShs1olNeXzW2DzyTvCjOeUSd7v905x/aZrJL9MjYV19bdO8KZbP17lyM1/b80cxR1POXAhwE0V3ZxWzGTERuTuNLJ8jeJXhw1stJMUH5rXk4koBOHSAJ8pAwVnAgtsPm0z44ytVbyP7ryITi3gzrV3X8PqKC/GohneURJ56p+p5hmBQlivSjqsP5+zhA5Yzav1/aIbZHdAF3oKm1ayk6BIl6vlcUneARumoyW68SRfkxl+W8+upv74T04Qfa1cXNBeQoQsaNGb4ceV7MeMzSCKfuTcykDmzabx1MvTK4/mSH/UF8uEf5fqsvu49wTJ4osqzfl7kvX9kK6Rdae8CGuudjw/now8wbmoxWlogSjappiZtITCD0ZZu/b3yorUnUE1K3/desRt9/bUUQ=
  app: sweater-weather-2105be
  on:
    repo: antoniojking/sweater_weather
    branch: main
