language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: tsSbd7jjty31LxuRFwbmyQcmzXxt3jhkcxlve7jWi2v+5umP/s963BXWsxwIAlVEmpU8rzCnyYPHaYcci5615igMXWcM/bBm8ub4LwySR2soebRAKWyImgNzXiPnl0oTyOgrFR1/oye1OpKpG4UfZ7g4icqRmWrdG9w7B56QkBY9FxoACHj/f34ZkMwOvkAkzi4K2rlFZLBpe5+LKVdgOY+B4dlhOMLifrg7P/PDykfX03mg5oj9/OC8Unt1NypFsG/Bt+1jQeOt+Rq2VnyPMk/zNUNYNC9j3MLLsJ3HUBW3/tOltF2YEK6n86zzVJIqYjwyzIcj4rrqs8+j9Mi5Nb5LvhIWTrHB9Z0Jnpqpbc8PA/gKSlMhg4s8i277zgCzKgYCWO+dcvMXxozZjGl6dPLB1A79g32IV1thcTGEj+kTR1GWMWtybvmy8xvGGa1G+RjI2xG+Ar5QmBmZN4aCRHht/H2GPC7QzveMyGUJMYRbvaF+1dxbg4LyxqOcKYT8ZFmLUsYG/AmzmosY9rvNAiUI7LRBFpJ7N6oAyW9I7rnfL+XGu4alNOYUyc3xTa+PtXOjY5+aFHysg6WCAZjYRcdIfyfpYd+q2yzap15rDHrAB1sk/HMIo23Y6r2bDPVHHXY6J4ZmZshQRQ85CcceJxGQJ1FPWtMfWL9PZtD+iLY=
  on:
    repo: antoniojking/sweater_weather
    branch: main
  app: sweater-weather-2105be
