language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 59f47a59-06ec-4084-9f9c-04ab195cf41f
  app: sweater-weather-2105be
  on:
    repo: antoniojking/sweater_weather
    branch: main
